### ISSUE TITLE
Stream data sent from Dynamo/GH not showing up in UI

### ISSUE THREAD

**Issue by izzylys** [speckleworks/SpeckleAdmin#32]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

(I've not posted an issue here before, so apologies if this is in the wrong place or anything)

#### Expected Behaviour
For a stream created manually in Hestia, there are four tabs across the top that let you see Overview, Sharing, Edit Data, and History. Your team members can go to the Edit Data tab and view the string/number data there in the UI.
![image](https://user-images.githubusercontent.com/7717434/53012986-6e04c800-343c-11e9-97ed-c6d6efe4dc56.png)

#### Actual Behaviour
I can send and receive the data in Dynamo, but there's no Data button in the UI for another team member to go look at the data I've sent to the stream. The data can also be viewed using the [API url](https://hestia.speckle.works/api/v1/streams/y2DlFS1Yt/) or by adding `/data` to the [UI URL](https://hestia.speckle.works/#/streams/y2DlFS1Yt/data)
![image](https://user-images.githubusercontent.com/7717434/53012308-8542b600-343a-11e9-8739-9df93aadf7ef.png)

![image](https://user-images.githubusercontent.com/7717434/53013015-870d7900-343c-11e9-88dd-4472577173bd.png)

#### Affected Projects
Don't think so; it's really not a huge problem since the data is still sent. It's just a little awkward for other team members to view the data in the UI if they're unfamiliar.

#### Reproduction Steps & System Config (win, osx, web, etc.)
Create a stream and send string/number data to it using the Speckle Sender in Dynamo then view it in the UI frontend. 

#### Proposed Solution (if any)
I imagine having a button for 'Data' in the menu so others can view the data even if they don't have permission to edit would be sufficient.

**Comment by didimitrie** [comment]
Hello @izzylys! This is a good thought you raised up. In theory, the data tab is only for viewing the stream's data only if it's marked as `onlineEditable=true`. Currently,  only by creating a stream from the online interface you can do this. 

The logic behind this "data view" would be completely different from the current one in order to handle (1) larger datasets and (2) things like geometry. 

What would be the usecase for this? There's several ways of solving this: 
- adding an option in the clients "mark as online editable", thereafter that tab will appear
- embarking on a proper "tabular" view effort for streams (which would be the sustainable way forward, but it's a lotta work and there's the classic resourcing problems at the moment) - unless you fancy learning some frontend 😎

**Comment by izzylys** [comment]
Ah ok that makes sense. I've only really been using this for calculation results and design data (rather than 3D), so our usecase for this has been to be able to view calcs that other people have done and pull these values into Revit or generate reports. Like I mentioned though, it's not really a big hindrance as I can just send people the `/data` page link for them to view. It totally works, it's just a bit awkward.

I'd honestly be keen to try and find a solution for a tabular stream view, but I wouldn't really know where to start! I don't have any knowledge about frontend, but maybe this is my call to learn haha

**Comment by didimitrie** [comment]
cleanup time; closing this - moved stuff to #52 for future reference; it was not really a bug :)
