### ISSUE TITLE
problems sharing speckle viewer 

### ISSUE THREAD

**Issue by tluth** [speckleworks/SpeckleAdmin#88]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
When I send someone a link to speckle viewer with a particular stream displayed (e.g. https://hestia.speckle.works/#/view/NDpZHyAWc) they should be able to open in a browser and see the building model.

#### Actual Behaviour
If the user has never logged into the speckle server before, they see a blank speckle viewer with no model selected.

#### Affected Projects
¯\_(ツ)_/¯ 

#### Reproduction Steps & System Config (win, osx, web, etc.)
Open an incognito window (clearing cookies would presumably have the same effect) in chrome, go here => https://hestia.speckle.works/#/view/NDpZHyAWc

#### Proposed Solution (if any)
¯\_(ツ)_/¯  I never noticed this in the past.. Maybe roll back whatever caused it?

**Comment by didimitrie** [comment]
This is fixed in the ci-ed version on [app.speckle.systems](https://app.speckle.systems/#/view/NDpZHyAWc?s=eyJzZXJ2ZXIiOiJodHRwczovL2hlc3RpYS5zcGVja2xlLndvcmtzL2FwaSIsImNhbWVyYSI6eyJ0YXJnZXQiOls3NS44NjE0NTMyMjM3MjMwNiwyNC4wNTA4MjcxMTcwNDc3OTUsMy43MzAxNTg3MzAxNTg3MzAyXSwicG9zaXRpb24iOlsxOTIuMDg1MzM1NzM2MDg0MTgsMTUzLjkyNzQ1NjAwNjgxMTEzLDQ3LjkyMjE4NTU2NTc5MTA3XSwicm90YXRpb24iOlstMS4yNDI4MjMzNjQ3ODQ1MTQyLDAuNzAyODU0MzkyMTAxNzU0OCwyLjkyNTA5NTMwNzIwNTk0OV19fQ).

Hestia's just behind the times now. I'm starting to regret the plugin infrastructure...
